## Creating single configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
data:
  {{- with .Values.application.configmap.properties1 -}}
  {{ toYaml . | nindent 2 }}
  {{- end -}}
  {{- with .Values.application.configmap.properties2 -}}
  {{ toYaml . | nindent 2 }}
  {{- end -}}
